### ISSUE TITLE
User should be able to search for public tutorials via searchbar on the discover page.

### ISSUE THREAD

**Issue by bbiehl** [omahacodeschool/fyiio#160]

**Comment by sumeetjain** [comment]
@bbiehl Is this your current task? If so, can you make a PR (even if empty) for it? And push regularly, so I can check in without having to bug you directly.

**Comment by bbiehl** [comment]
https://github.com/omahacodeschool/fyiio/pull/161

Here's the PR.  I'm working on getting the search to actually search for tutorials, chapters, and steps that match up with user's query.

**Comment by bbiehl** [comment]
Can search tutorials.
